server:
  port: 8190
  servlet:
    context-path: /market-carts
integrations:
  product-service:
    url: http://localhost:8080/market
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
cart-service:
  cart-prefix: winterMarket_cart_
